# Generated by Django 2.1.1 on 2018-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180926_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
