# Generated by Django 2.1.1 on 2018-09-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180926_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='type',
            new_name='handler_type',
        ),
    ]
